#docker-compose should be install #URL # https://docs.docker.com/compose/install/ 
#docker-compose up # to start
#docker-compose down -v # to remove
#docker ps -a # remove all the conatiner
#docker network ls  #remove all un-used network #docker network prune

version: '2'
services:
 drupal:
         build: .
         image: custom-druple
         ports:
          - "9090:80"
		 volumes:
		  - drupal-modules:/var/www/html/modules
          - drupal-profiles:/var/www/html/profiles
          - drupal-sites:/var/www/html/sites
          - drupal-themes:/var/www/html/themes  
 postgres:
         image: postgres:9.6
		 environment:
		  - POSTGRES_PASSWORD=mypassword
		 volumes:
		  - drupal-data:/var/lib/postgresql/data
volumes:
 drupal-data:
 drupal-modules:
 drupal-profiles:
 drupal-sites:
 drupal-themes:
